url: "http://hcubism.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "H-Cubism" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-paginate-v2

sass:
  implementation: sass-embedded
  sourcemap: development
  style: compressed

postcss:
  cache: false

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_reverse: true

highlighter: none
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
